Maded common* and expression* as similar as possible. Also, restored the ast_adapated.hpp includes to *.cpp files.
Still getting the link error:

/tmp/build/clangxx3_8_pkg/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/common.o: In function `bool boost::spirit::x3::rule<count_class, ast::Count, false>::parse<std::__1::__wrap_iter<char const*>, boost::spirit::x3::unused_type, ast::Start>(std::__1::__wrap_iter<char const*>&, std::__1::__wrap_iter<char const*> const&, boost::spirit::x3::unused_type const&, boost::spirit::x3::unused_type, ast::Start&) const':
common.cpp:(.text._ZNK5boost6spirit2x34ruleI11count_classN3ast5CountELb0EE5parseINSt3__111__wrap_iterIPKcEENS1_11unused_typeENS4_5StartEEEbRT_RKSF_RKT0_SD_RT1_[_ZNK5boost6spirit2x34ruleI11count_classN3ast5CountELb0EE5parseINSt3__111__wrap_iterIPKcEENS1_11unused_typeENS4_5StartEEEbRT_RKSF_RKT0_SD_RT1_]+0x3c): undefined reference to `bool parse_rule<std::__1::__wrap_iter<char const*>, boost::spirit::x3::unused_type, ast::Start>(boost::spirit::x3::rule<count_class, ast::Count, false>, std::__1::__wrap_iter<char const*>&, std::__1::__wrap_iter<char const*> const&, boost::spirit::x3::unused_type const&, ast::Start&)'
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)

The strange thing about that link error is the argument list:

( boost::spirit::x3::rule<count_class, ast::Count, false>
, std::__1::__wrap_iter<char const*>&
, std::__1::__wrap_iter<char const*> const&
, boost::spirit::x3::unused_type const&
, ast::Start&
)

is that it has ast::Start as the attribute,
but the rule is for the count_class.

I maybe missing something :(