In attempt to use "consistent" args among the
BOOST_SPIRIT_{DEFINE,DECLARE,INSTANTIATE} macros, added use
of std::declval; however, not getting compile errors
elsewhere:

-*- mode: compilation; default-directory: "~/prog_dev/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/" -*-
Compilation started at Wed Nov  9 12:26:44

make -f ../linkerr.mk MAIN=prog x -Wcommon.cpp
install -d `dirname /tmp/build/clangxx3_8_pkg/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/prog.o`
/home/evansl/dwnlds/llvm/3.8/prebuilt/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang++ -c -O0 -stdlib=libc++  -std=c++14 -ftemplate-backtrace-limit=0 -fdiagnostics-show-template-tree -fno-elide-type -fmacro-backtrace-limit=0     -I/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0    -ftemplate-depth=200  prog.cpp -MMD -o /tmp/build/clangxx3_8_pkg/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/prog.o
In file included from prog.cpp:1:
In file included from ./common.hpp:3:
In file included from ./ast_adapted.hpp:10:
In file included from ./ast.hpp:2:
In file included from /home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3.hpp:17:
In file included from /home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/nonterminal.hpp:10:
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/nonterminal/rule.hpp:35:9: error: static_assert
      failed "BOOST_SPIRIT_DEFINE undefined for this rule."
        static_assert(!is_same<decltype(get<ID>(context)), unused_type>::value,
        ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/nonterminal/rule.hpp:116:20: note: in
      instantiation of function template specialization 'boost::spirit::x3::parse_rule<start_class, ast::Start,
      std::__1::__wrap_iter<const char *>, boost::spirit::x3::unused_type, ast::Start>' requested here
            return parse_rule(*this, first, last, context, attr);
                   ^
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/core/parse.hpp:35:29: note: in instantiation of
      function template specialization 'boost::spirit::x3::rule<start_class, ast::Start,
      false>::parse<std::__1::__wrap_iter<const char *>, boost::spirit::x3::unused_type, ast::Start>' requested here
        return as_parser(p).parse(first, last, unused, unused, attr);
                            ^
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/core/parse.hpp:47:16: note: in instantiation of
      function template specialization 'boost::spirit::x3::parse_main<std::__1::__wrap_iter<const char *>,
      boost::spirit::x3::rule<start_class, ast::Start, false>, ast::Start>' requested here
        return parse_main(first, last, p, attr);
               ^
prog.cpp:8:14: note: in instantiation of function template specialization
      'boost::spirit::x3::parse<std::__1::__wrap_iter<const char *>, boost::spirit::x3::rule<start_class, ast::Start,
      false>, ast::Start>' requested here
  return x3::parse(iter, end, start_rule(), attr);
             ^
In file included from prog.cpp:1:
In file included from ./common.hpp:3:
In file included from ./ast_adapted.hpp:10:
In file included from ./ast.hpp:2:
In file included from /home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3.hpp:17:
In file included from /home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/nonterminal.hpp:10:
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/nonterminal/rule.hpp:37:33: error: no member
      named 'parse' in 'boost::spirit::x3::unused_type'
        return get<ID>(context).parse(first, last, context, unused, attr);
               ~~~~~~~~~~~~~~~~ ^
2 errors generated.
/home/evansl/prog_dev/root.imk:169: recipe for target '/tmp/build/clangxx3_8_pkg/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/prog.o' failed
make: *** [/tmp/build/clangxx3_8_pkg/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/prog.o] Error 1

Compilation exited abnormally with code 2 at Wed Nov  9 12:26:45