Still link fails when pass_through flag is set to
true for rules:

-*- mode: compilation; default-directory: "~/prog_dev/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/" -*-
Compilation started at Sat Nov 12 17:12:50

make -f ../linkerr.mk MAIN=prog run
install -d `dirname /tmp/build/gcc5_2_0/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/linker_err_msg.o`
/home/evansl/dwnlds/gcc/5.2.0/install/bin/g++ -c -O0    -O0 -gdwarf-2 -std=c++17 -Wall -Wno-deprecated -Wstrict-overflow -ftemplate-depth-200  -Wno-unused-local-typedefs -Wno-unused-but-set-variable  -I/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0    -ftemplate-depth=200  linker_err_msg.cpp -MMD -o /tmp/build/gcc5_2_0/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/linker_err_msg.o
sed -e 's#^linker_err_msg.o:#/tmp/build/gcc5_2_0/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/linker_err_msg.o:#' /tmp/build/gcc5_2_0/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/linker_err_msg.d> /tmp/build/gcc5_2_0/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/linker_err_msg.o.dep
rm /tmp/build/gcc5_2_0/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/linker_err_msg.d
/home/evansl/dwnlds/gcc/5.2.0/install/bin/g++ -Wl,--library-path=/home/evansl/dwnlds/gcc/5.2.0/install/lib64 -Wl,-rpath=/home/evansl/dwnlds/gcc/5.2.0/install/lib64  /tmp/build/gcc5_2_0/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/prog.o /tmp/build/gcc5_2_0/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/common.o /tmp/build/gcc5_2_0/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/expression.o /tmp/build/gcc5_2_0/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/linker_err_msg.o  -o /tmp/build/gcc5_2_0/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/prog.exe
/tmp/build/gcc5_2_0/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/common.o: In function `bool boost::spirit::x3::rule<count_class, ast::Count, true>::parse<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::spirit::x3::context<start_class, boost::spirit::x3::sequence<boost::spirit::x3::omit_directive<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard> >, boost::spirit::x3::rule<count_class, ast::Count, true> > const, boost::spirit::x3::unused_type>, ast::Start>(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&, boost::spirit::x3::context<start_class, boost::spirit::x3::sequence<boost::spirit::x3::omit_directive<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard> >, boost::spirit::x3::rule<count_class, ast::Count, true> > const, boost::spirit::x3::unused_type> const&, boost::spirit::x3::unused_type, ast::Start&) const':
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/nonterminal/rule.hpp:116: undefined reference to `bool parse_rule<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::spirit::x3::context<start_class, boost::spirit::x3::sequence<boost::spirit::x3::omit_directive<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard> >, boost::spirit::x3::rule<count_class, ast::Count, true> > const, boost::spirit::x3::unused_type>, ast::Start>(boost::spirit::x3::rule<count_class, ast::Count, true>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&, boost::spirit::x3::context<start_class, boost::spirit::x3::sequence<boost::spirit::x3::omit_directive<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard> >, boost::spirit::x3::rule<count_class, ast::Count, true> > const, boost::spirit::x3::unused_type> const&, ast::Start&)'
collect2: error: ld returned 1 exit status
/home/evansl/prog_dev/root.imk:200: recipe for target '/tmp/build/gcc5_2_0/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/prog.exe' failed
make: *** [/tmp/build/gcc5_2_0/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/prog.exe] Error 1

Compilation exited abnormally with code 2 at Sat Nov 12 17:12:50