when defined(KEEP_CHAR), compile error:
-*- mode: compilation; default-directory: "~/prog_dev/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/" -*-
Compilation started at Thu Nov 10 04:38:10

make -f ../linkerr.mk MAIN=prog x
install -d `dirname /tmp/build/clangxx3_8_pkg/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/common.o`
/home/evansl/dwnlds/llvm/3.8/prebuilt/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang++ -c -O0 -stdlib=libc++  -std=c++14 -ftemplate-backtrace-limit=0 -fdiagnostics-show-template-tree -fno-elide-type -fmacro-backtrace-limit=0     -I/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0    -ftemplate-depth=200  common.cpp -MMD -o /tmp/build/clangxx3_8_pkg/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/common.o
In file included from common.cpp:2:
In file included from ./ast_adapted.hpp:10:
In file included from ./ast.hpp:2:
In file included from /home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3.hpp:19:
In file included from /home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/operator.hpp:10:
In file included from /home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/operator/sequence.hpp:12:
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/operator/detail/sequence.hpp:143:9: error:
      static_assert failed "Attribute does not have the expected size."
        static_assert(
        ^
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/operator/detail/sequence.hpp:302:26: note:
      in instantiation of template class
      'boost::spirit::x3::detail::partition_attribute<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard>,
      boost::spirit::x3::rule<count_class, ast::Count, false>, ast::Start, boost::spirit::x3::unused_type, void>'
      requested here
        typedef typename partition::l_pass l_pass;
                         ^
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/operator/sequence.hpp:44:28: note: in
      instantiation of function template specialization
      'boost::spirit::x3::detail::parse_sequence<boost::spirit::x3::sequence<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard>,
      boost::spirit::x3::rule<count_class, ast::Count, false> >, std::__1::__wrap_iter<const char *>,
      boost::spirit::x3::unused_type, ast::Start, ast::Start>' requested here
            return detail::parse_sequence(*this, first, last, context, rcontext, attr
                           ^
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/nonterminal/detail/rule.hpp:206:26: note: in
      instantiation of function template specialization
      'boost::spirit::x3::sequence<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard>,
      boost::spirit::x3::rule<count_class, ast::Count, false> >::parse<std::__1::__wrap_iter<const char *>,
      boost::spirit::x3::unused_type, ast::Start, ast::Start>' requested here
            bool r = rhs.parse(
                         ^
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/nonterminal/detail/rule.hpp:266:20: note: in
      instantiation of function template specialization 'boost::spirit::x3::detail::rule_parser<ast::Start,
      start_class>::parse_rhs_main<boost::spirit::x3::sequence<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard>,
      boost::spirit::x3::rule<count_class, ast::Count, false> >, std::__1::__wrap_iter<const char *>,
      boost::spirit::x3::unused_type, ast::Start, ast::Start>' requested here
            return parse_rhs_main(
                   ^
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/nonterminal/detail/rule.hpp:280:20: note: in
      instantiation of function template specialization 'boost::spirit::x3::detail::rule_parser<ast::Start,
      start_class>::parse_rhs_main<boost::spirit::x3::sequence<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard>,
      boost::spirit::x3::rule<count_class, ast::Count, false> >, std::__1::__wrap_iter<const char *>,
      boost::spirit::x3::unused_type, ast::Start, ast::Start>' requested here
            return parse_rhs_main(rhs, first, last, context, rcontext, attr);
                   ^
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/nonterminal/detail/rule.hpp:332:28: note: in
      instantiation of function template specialization 'boost::spirit::x3::detail::rule_parser<ast::Start,
      start_class>::parse_rhs<boost::spirit::x3::sequence<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard>,
      boost::spirit::x3::rule<count_class, ast::Count, false> >, std::__1::__wrap_iter<const char *>,
      boost::spirit::x3::unused_type, ast::Start, ast::Start>' requested here
                ok_parse = parse_rhs(rhs, first, last, context, attr_, attr_
                           ^
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/nonterminal/rule.hpp:64:19: note: in
      instantiation of function template specialization 'boost::spirit::x3::detail::rule_parser<ast::Start,
      start_class>::call_rule_definition<boost::spirit::x3::sequence<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard>,
      boost::spirit::x3::rule<count_class, ast::Count, false> >, std::__1::__wrap_iter<const char *>,
      boost::spirit::x3::unused_type, ast::Start, mpl_::bool_<false> >' requested here
                ::call_rule_definition(
                  ^
./common_def.hpp:17:1: note: in instantiation of function template specialization
      'boost::spirit::x3::rule_definition<start_class,
      boost::spirit::x3::sequence<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard>,
      boost::spirit::x3::rule<count_class, ast::Count, false> >, ast::Start, false>::parse<std::__1::__wrap_iter<const
      char *>, boost::spirit::x3::unused_type, ast::Start>' requested here
BOOST_SPIRIT_DEFINE(start);
^
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/nonterminal/rule.hpp:170:5: note: expanded
      from macro 'BOOST_SPIRIT_DEFINE'
    BOOST_SPIRIT_DEFINE_, _, BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__))             \
    ^
In file included from common.cpp:2:
In file included from ./ast_adapted.hpp:10:
In file included from ./ast.hpp:2:
In file included from /home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3.hpp:19:
In file included from /home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/operator.hpp:10:
In file included from /home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/operator/sequence.hpp:12:
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/operator/detail/sequence.hpp:303:37: error:
      no type named 'r_pass' in
      'boost::spirit::x3::detail::partition_attribute<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard>,
      boost::spirit::x3::rule<count_class, ast::Count, false>, ast::Start, boost::spirit::x3::unused_type, void>'
        typedef typename partition::r_pass r_pass;
                ~~~~~~~~~~~~~~~~~~~~^~~~~~
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/operator/sequence.hpp:44:28: note: in
      instantiation of function template specialization
      'boost::spirit::x3::detail::parse_sequence<boost::spirit::x3::sequence<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard>,
      boost::spirit::x3::rule<count_class, ast::Count, false> >, std::__1::__wrap_iter<const char *>,
      boost::spirit::x3::unused_type, ast::Start, ast::Start>' requested here
            return detail::parse_sequence(*this, first, last, context, rcontext, attr
                           ^
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/nonterminal/detail/rule.hpp:206:26: note: in
      instantiation of function template specialization
      'boost::spirit::x3::sequence<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard>,
      boost::spirit::x3::rule<count_class, ast::Count, false> >::parse<std::__1::__wrap_iter<const char *>,
      boost::spirit::x3::unused_type, ast::Start, ast::Start>' requested here
            bool r = rhs.parse(
                         ^
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/nonterminal/detail/rule.hpp:266:20: note: in
      instantiation of function template specialization 'boost::spirit::x3::detail::rule_parser<ast::Start,
      start_class>::parse_rhs_main<boost::spirit::x3::sequence<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard>,
      boost::spirit::x3::rule<count_class, ast::Count, false> >, std::__1::__wrap_iter<const char *>,
      boost::spirit::x3::unused_type, ast::Start, ast::Start>' requested here
            return parse_rhs_main(
                   ^
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/nonterminal/detail/rule.hpp:280:20: note: in
      instantiation of function template specialization 'boost::spirit::x3::detail::rule_parser<ast::Start,
      start_class>::parse_rhs_main<boost::spirit::x3::sequence<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard>,
      boost::spirit::x3::rule<count_class, ast::Count, false> >, std::__1::__wrap_iter<const char *>,
      boost::spirit::x3::unused_type, ast::Start, ast::Start>' requested here
            return parse_rhs_main(rhs, first, last, context, rcontext, attr);
                   ^
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/nonterminal/detail/rule.hpp:332:28: note: in
      instantiation of function template specialization 'boost::spirit::x3::detail::rule_parser<ast::Start,
      start_class>::parse_rhs<boost::spirit::x3::sequence<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard>,
      boost::spirit::x3::rule<count_class, ast::Count, false> >, std::__1::__wrap_iter<const char *>,
      boost::spirit::x3::unused_type, ast::Start, ast::Start>' requested here
                ok_parse = parse_rhs(rhs, first, last, context, attr_, attr_
                           ^
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/nonterminal/rule.hpp:64:19: note: in
      instantiation of function template specialization 'boost::spirit::x3::detail::rule_parser<ast::Start,
      start_class>::call_rule_definition<boost::spirit::x3::sequence<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard>,
      boost::spirit::x3::rule<count_class, ast::Count, false> >, std::__1::__wrap_iter<const char *>,
      boost::spirit::x3::unused_type, ast::Start, mpl_::bool_<false> >' requested here
                ::call_rule_definition(
                  ^
./common_def.hpp:17:1: note: in instantiation of function template specialization
      'boost::spirit::x3::rule_definition<start_class,
      boost::spirit::x3::sequence<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard>,
      boost::spirit::x3::rule<count_class, ast::Count, false> >, ast::Start, false>::parse<std::__1::__wrap_iter<const
      char *>, boost::spirit::x3::unused_type, ast::Start>' requested here
BOOST_SPIRIT_DEFINE(start);
^
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/nonterminal/rule.hpp:170:5: note: expanded
      from macro 'BOOST_SPIRIT_DEFINE'
    BOOST_SPIRIT_DEFINE_, _, BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__))             \
    ^
In file included from common.cpp:2:
In file included from ./ast_adapted.hpp:10:
In file included from ./ast.hpp:2:
In file included from /home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3.hpp:19:
In file included from /home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/operator.hpp:10:
In file included from /home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/operator/sequence.hpp:12:
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/operator/detail/sequence.hpp:305:29: error:
      no type named 'l_part' in
      'boost::spirit::x3::detail::partition_attribute<boost::spirit::x3::any_char<boost::spirit::char_encoding::standard>,
      boost::spirit::x3::rule<count_class, ast::Count, false>, ast::Start, boost::spirit::x3::unused_type, void>'
        typename partition::l_part l_part = partition::left(attr);
        ~~~~~~~~~~~~~~~~~~~~^~~~~~
3 errors generated.
/home/evansl/prog_dev/root.imk:169: recipe for target '/tmp/build/clangxx3_8_pkg/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/common.o' failed
make: *** [/tmp/build/clangxx3_8_pkg/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/common.o] Error 1

Compilation exited abnormally with code 2 at Thu Nov 10 04:38:11