Same compile error occurs with boost_1_60_0:
/home/evansl/dwnlds/llvm/3.8/prebuilt/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang++ -c -O0 -stdlib=libc++  -std=c++14 -ftemplate-backtrace-limit=0 -fdiagnostics-show-template-tree -fno-elide-type -fmacro-backtrace-limit=0     -I/home/evansl/prog_dev/boost/releases/ro/boost_1_60_0    -ftemplate-depth=200  common.cpp -MMD -o /tmp/build/clangxx3_8_pkg/clang/dwnlds_work/dwnlds/Gerell.Boost_1_61_Spirit.LinkError.clone/cppljevans.boost_1_61_problem/common.o
In file included from common.cpp:2:
In file included from ./ast_adapted.hpp:10:
In file included from ./ast.hpp:2:
In file included from /home/evansl/prog_dev/boost/releases/ro/boost_1_60_0/boost/spirit/home/x3.hpp:19:
In file included from /home/evansl/prog_dev/boost/releases/ro/boost_1_60_0/boost/spirit/home/x3/operator.hpp:10:
In file included from /home/evansl/prog_dev/boost/releases/ro/boost_1_60_0/boost/spirit/home/x3/operator/sequence.hpp:12:
/home/evansl/prog_dev/boost/releases/ro/boost_1_60_0/boost/spirit/home/x3/operator/detail/sequence.hpp:143:9: error:
      static_assert failed "Attribute does not have the expected size."
        static_assert(
        ^
.
.
.